[[libftdi]]
arch = "i686"
git-tree-sha1 = "85ab6ebcb5d69827ad5e9167f7e6bf510e4a309d"
libc = "glibc"
os = "linux"

    [[libftdi.download]]
    sha256 = "1f1c075738eec718c358aa678d9eea3d413a3441e7ba273de5dd49dcf80473f5"
    url = "https://github.com/jqfeld/libftdi_jll.jl/releases/download/libftdi-v1.5.0+0/libftdi.v1.5.0.i686-linux-gnu.tar.gz"
[[libftdi]]
arch = "i686"
git-tree-sha1 = "6aed48430146f5c99b549482c303aea69f4db0d7"
os = "windows"

    [[libftdi.download]]
    sha256 = "a54e4de7d8e4012fc49f23989a89e32e686e4e5161c9417fc4808dc7ce48d036"
    url = "https://github.com/jqfeld/libftdi_jll.jl/releases/download/libftdi-v1.5.0+0/libftdi.v1.5.0.i686-w64-mingw32.tar.gz"
[[libftdi]]
arch = "x86_64"
git-tree-sha1 = "f87834e7e9007551cf5cff9e9a9ecacf56314eaf"
libc = "glibc"
os = "linux"

    [[libftdi.download]]
    sha256 = "a146249aa0786a54e15caebe51e7ab50ce99ff64984398818485ea7d441465a9"
    url = "https://github.com/jqfeld/libftdi_jll.jl/releases/download/libftdi-v1.5.0+0/libftdi.v1.5.0.x86_64-linux-gnu.tar.gz"
[[libftdi]]
arch = "x86_64"
git-tree-sha1 = "2c3882ca4416d5de4e3353dccdb863d63f0ef21b"
os = "windows"

    [[libftdi.download]]
    sha256 = "f0819141216a62cf7e01c658f6dd66d346dfe24b06796c4121e528e2b71cfc4f"
    url = "https://github.com/jqfeld/libftdi_jll.jl/releases/download/libftdi-v1.5.0+0/libftdi.v1.5.0.x86_64-w64-mingw32.tar.gz"
