# Autogenerated wrapper script for libftdi_jll for i686-w64-mingw32
export libftdi

using libusb_jll
using libconfuse_jll
JLLWrappers.@generate_wrapper_header("libftdi")
JLLWrappers.@declare_library_product(libftdi, "libftdi1.dll")
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll, libconfuse_jll)
    JLLWrappers.@init_library_product(
        libftdi,
        "bin\\libftdi1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
