# Autogenerated wrapper script for libftdi_jll for i686-linux-gnu
export libftdi

using libusb_jll
using libconfuse_jll
JLLWrappers.@generate_wrapper_header("libftdi")
JLLWrappers.@declare_library_product(libftdi, "libftdi1.so.2")
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll, libconfuse_jll)
    JLLWrappers.@init_library_product(
        libftdi,
        "lib/libftdi1.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
